uploads = []
generated = []

[[outputs]]
id = "t5uU1OGi2r7qa1quyrY0u"
uri = "file://leo-os-data-export.zip"
type = "unspecified"
title = "LEO OS — Data Export (SQL + Excel)"

[[outputs]]
id = "4rXf2khHenX8vfD_6Pr84"
uri = "file://billing-expenses-export.xlsx"
type = "table"
title = "Billing & Expenses Export"

[[outputs]]
id = "_7F5QBmx8Iot8hlGNYLj8"
uri = "file://leo-os-full-dump.zip"
type = "unspecified"
title = "LEO OS — Full Database Dump (SQL)"

[[outputs]]
id = "uoSvUCia7cRgPV9hwPpKa"
uri = "file://billing-detail-export.xlsx"
type = "table"
title = "Billing Details & Expenses Export"
