uploads = []

[[generated]]
id = "UO5C86IxwfMQLOQRAm2Tx"
uri = "file://artifacts/passport-ocr-admin/assets/images/icon.png"
type = "image"
title = "neon-green-briefcase-icon"

[[outputs]]
id = "Mf7VMyMT922dqQmV3Ee0B"
uri = "file://artifacts/passport-ocr-admin/assets/images/icon.png"
type = "image"

[[outputs]]
id = "gblrzjUl-WcsJrCkRE_9e"
uri = "file://leo_os_export.sql.gz"
type = "unspecified"
title = "LEO OS — Production Database Export (.sql.gz)"

[[outputs]]
id = "nKn3gXTksJ-IT2lK0LqWS"
uri = "file://LEO_OS_Developer_Guide.md"
type = "text"
title = "LEO OS — Full Developer Guide"
